module RCRM
  class Applicant < Selection
    self.valid_fields = %i(
      addresses
      applicantActions
      applicantId
      applicantName
      applicantSurname
      assessedBy
      assessedByValue
      assessmentDate
      attributes
      availability
      availabilityId
      availableDate
      consultantGroups
      consultantUsers
      createdOn
      createdUserId
      createdUserName
      currentBasic
      currentPackage
      cvs
      desiredJobTitle
      dob
      employmentTypeDescription
      employmentTypeIdCsv
      fileAs
      flagText
      formUrl
      gdprConsents
      gender
      genderValueId
      imageUrl
      jobTitle
      location
      locationDescription
      locationId
      mailshotOptions
      maritalStatus
      maritalStatusValueId
      minBasic
      minPackage
      nationality
      nationalityId
      notebookItems
      personId
      phones
      primaryEmailAddress
      primaryEmailAddressPhoneId
      primaryPhoneId
      primaryPhoneNo
      priority
      priorityValueId
      rateUnit
      rateUnitDetails
      salutation
      sectorIdCsv
      source
      sourceId
      status
      statusDate
      statusId
      title
      titleValueId
      updatedOn
      updatedUserId
      updatedUserName
      workHistories
    )

    def default_fields
      %i(applicantId applicantName applicantSurname fileAs primaryEmailAddress)
    end
  end
end
