module RCRM
  class InsertApplicantInput < Input
    valid_fields = %i(
      availableDate
      statusId
      statusDate
      priorityValueId
      jobTitle
      desiredJobTitle
      minBasic
      currentBasic
      minPackage
      currentPackage
      rateUnit
      sourceId
      locationId
      availabilityId
      applicantName
      applicantSurname
      assessmentDate
      assessedBy
      createdUserId
      createdUserName
      updatedUserId
      updatedUserName
      dob
      genderValueId
      maritalStatusValueId
      nationalityId
      salutation
      titleValueId
      sectorIdCsv
      fileAs
      flagText
      employmentTypeIdCsv
      primaryPhoneId
    )
  end
end
