module RCRM
  class UpdateApplicantInput < Input
    self.valid_fields = %i(
      applicantId
      availableDate
      statusId
      priorityValueId
      jobTitle
      desiredJobTitle
      minBasic
      currentBasic
      minPackage
      currentPackage
      rateUnit
      sourceId
      locationId
      availabilityId
      applicantName
      applicantSurname
      assessmentDate
      assessedBy
      primaryEmailAddressPhoneId
      createdUserId
      createdUserName
      updatedUserId
      updatedUserName
      dob
      genderValueId
      maritalStatusValueId
      nationalityId
      salutation
      titleValueId
      sectorIdCsv
      fileAs
      flagText
      employmentTypeIdCsv
      primaryPhoneId
    )
  end
end
